version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    install:
        working_directory: ~/app
        docker:
            - image: vdtn359/node-pnpm-base:16-alpine-7.9.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install
                  command: pnpm install --frozen-lockfile
            - save_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - node_modules
                        - .
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    test:
        docker:
            - image: vdtn359/node-pnpm-base:16-alpine-7.9.0
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Build
                  command: npm run build:all
            - run:
                  name: Lint
                  command: npm run lint:all
            - run:
                  name: Test
                  command: npm run test:all
workflows:
    version: 2
    build_and_test:
        jobs:
            - install
            - test:
                  requires:
                      - install
