version: '2.1'
workflows:
    version: '2'
    build_and_tests:
        jobs:
            - pass
jobs:
    pass:
        machine: true
        steps:
            - run:
                  description: Pass
                  command: echo 'pass'
